server:
  port: 8091

spring:
  application:
    name: plazoleta-plazoleta-ms
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta_plazoleta
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

microservices:
  users:
    url: http://localhost:8090
  messaging:
    url: http://localhost:8092
  traceability:
    url: http://localhost:8093

security:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration-millis: ${JWT_EXPIRATION_MILLIS:300000}
